apiVersion: v1
kind: Service
metadata:
  {{- if eq .Values.springApp.service.type "LoadBalancer" }}
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: {{ .Values.springApp.dnsPrefix }}
  {{- end }}
  name: app-svc
  namespace: {{ .Values.namespace.name }}
spec:
  type: {{ .Values.springApp.service.type }}
  ports:
  - name: "http-80"
    port: 80
    targetPort: 8080
  selector:
    app: app
    
