apiVersion: v1
kind: Service
metadata:
  {{- if not .Values.istioInjection.enabled }}
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: {{ .Values.dnsPrefix }}
  {{- end }}
  name: app-svc
  namespace: {{ .Values.namespace.name }}
spec:
  {{- if .Values.istioInjection.enabled }}
  type: ClusterIP
  {{- else }}
  type: LoadBalancer
  {{- end }}
  ports:
  - name: "http-80"
    port: 80
    targetPort: 8080
  selector:
    app: app
    