namespace:
  name: aulainfra

tz: "America/Sao_Paulo"

istioInjection:
  enabled: false

springApp:
  replicas: 1
  image:
    repository: jhvs1984
    name: spring-app:latest
  readinessProbe:
    enabled: true
  livenessProbe:
    enabled: true
  dnsPrefix: springpetapp
  service:
    type: NodePort

mysql:
  namespaceOverride: aulainfra
  architecture: standalone
  auth:
    rootPassword: "root"
    createDatabase: true
    database: petclinic
  primary:
    podLabels:
      app: mysqldb-stfs
