namespace:
  name: aulainfra
  
tz: "America/Sao_Paulo"

mySQLdb:
  volumeClaimTemplates:
    metadata:
      name: db-claim
    resources:
      requests:
        storage: 10Gi

springApp:
  replicas: 1
  image:
    repository: aulainfraacrk.azurecr.io
    name: springapp:latest

readinessProbe:
  enabled: true

livenessProbe:
  enabled: true

dnsPrefix: springpetapp

istioInjection:
  enabled: false